server:
  port: 1717
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employees
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

